server:
  port: 8080

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

#????
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  application:
    name: caryan
  mvc:
    static-path-pattern: /**
  datasource:
    dynamic:
      primary: base
      strict: false
      datasource:
        base:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/volunteer-register-sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: TJL123456.
          driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    #    port:
    host: smtp.163.com
    username: 15716273511@163.com
    password: DMggH5gSGKYYhM7d
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enabled: true
            required: false
        debug: true

  profiles:
    include: define,xxl-job
  redis:
    host: 120.26.203.21
    port: 6379
    password: J9ah3h4kaM918
    # ??????
    timeout: 15s
    lettuce:
      pool:
        # ???????????
        min-idle: 0
        # ???????????
        max-idle: 20
        # ????????????
        max-active: 20
        # #???????????????????????
        max-wait: 15000ms
    database: 5
  #????????redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #jackson???????????????
    time-zone: GMT+8
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    #    ????sql?????INFO?WARN?ERROR?????DEBUG???
    com.zhijian.cloud.dao: INFO
#  config: classpath:logging-spring.xml

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl









